#服务器端口
server:
  port: 7200

spring:
  datasource:
    url: jdbc:mysql://192.168.1.3/uupush?characterEncoding=utf-8&useSSL=false
    username: root
    password: "@Dccshop2017"
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 10
      connection-timeout: 60000
      minimum-idle: 5
      idle-timeout: 60000
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  redis:
    database: 0
    host: 39.107.80.193
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
  rabbitmq:
    host: 192.168.1.3
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
logging:
  level:
    ink.hcode.cloud.springcloudconsumerfeign.feign.MyFeignClient: DEBUG  
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true  
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic      