server:
  port: 80
zuul:
  routes:
    uupush-content: /content/**
    uupush-iterm: /iterm/**
    uupush-order: /order/**
    uupush-sso: /sso/**
    uupush-solr: /solr/**
    uupush-user: /user/**
    uupush-manager: /manager/**