#服务器端口

  redis:
    database: 0      # Redis数据库索引（默认为0）
    host: 39.107.80.193  # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password:        # Redis服务器连接密码（默认为空）
    timeout: 0       # 连接超时时间（毫秒）
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8    # 连接池中的最大空闲连接
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0    # 连接池中的最小空闲连接    
            
logging:
  level:
    ink.hcode.cloud.springcloudconsumerfeign.feign.MyFeignClient: DEBUG  
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true  
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic      